name: C/C++ CI

on: [push, workflow_dispatch]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install packages
      run: sudo apt update && sudo apt -y install g++-aarch64-linux-gnu      
    - name: Build project logfile amd64
      run: g++ -std=c++17 -o logfile_wrapper_amd64 logfile.cpp
    - name: Build project logfile arm64
      run: aarch64-linux-gnu-g++ -std=c++17 -o logfile_wrapper_arm64 logfile.cpp  
    - name: Build project fivem amd64
      run: g++ -std=c++17 -o fivem_wrapper_amd64 fivem.cpp            
    - name: ls
      run: ls -la
    - name: move
      run: |
        mkdir build
        mv logfile_wrapper_* build/
        mv fivem_wrapper_* build/
    - uses: actions/upload-artifact@v3
      with:
        path: build/*
