name: C/C++ CI

on: [push, workflow_dispatch]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      run: g++ -std=c++17 -o wrapper main.cpp
    - name: ls
      run: ls -la
    - uses: actions/upload-artifact@v2
      with:
        path: wrapper
        name: wrapper
