name: C/C++ CI

on: [push, workflow_dispatch]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install packages
      run: sudo apt -y install g++-aarch64-linux-gnu      
    - name: Build project amd64
      run: g++ -std=c++17 -o wrapper_amd64 main.cpp
    - name: Build project amd64
      run: aarch64-linux-gnu-g++ -std=c++17 -o wrapper_arm64 main.cpp      
    - name: ls
      run: ls -la
    - name: move
      run: |
        mkdir build
        mv wrapper_* build/
    - uses: actions/upload-artifact@v3.1.2
      with:
        path: build/*
